name: CISC3142Lab4
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: directory change
      run: cd ..
    - run: cd ..
    - run: echo "Running Makefile for Lab4"
    - name: Run Make for Lab4
      run: make
