name: CISC3142Lab4
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - run: echo "Running Makefile"
    - name: Run Make
      run: make -f makefile
