name: Hello World
on: [push]
  workflow_dispatch:
jobs:
  HelloWorld:
    runs-on: macos-latest
    #steps is the indivual actions done in a single push
    steps:
      -uses: actions/checkout@v2
      -run: echo "Running makefile"
      -name: create prog
       run: echo -e '#include <iostream>\n int main(){std::cout << "Hello World";}' > hello.cpp
      -run: g++ hello.cpp -o hello.out && ./hello.out